'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace WSOutsourcing
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://132.248.180.207/wsfesaoutsorcing", ConfigurationName:="WSOutsourcing.OutsourcingSoap")>  _
    Public Interface OutsourcingSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/insertaPersona", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertaPersona(ByVal strRfc As String, ByVal strHomoclaveRfc As String, ByVal strNombre As String, ByVal strApellidoPaterno As String, ByVal strApellidoMaterno As String, ByVal strTelefono As String, ByVal strCelular As String, ByVal strCorreoElectronico As String, ByVal strCalle As String, ByVal strColonia As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultarPersonas", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultarPersonas(ByVal strApellidoPaterno As String, ByVal strApellidoMaterno As String, ByVal strNombre As String, ByVal strRfc As String, ByVal strHomoclaveRfc As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultarColonia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultarColonia(ByVal strCodigoPostal As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultaNombrePersona", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultaNombrePersona(ByVal strRfc As String, ByVal strHomoclaveRfc As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/insertaUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertaUsuario(ByVal intIdPersona As Integer, ByVal strUsuario As String, ByVal strPassword As String, ByVal intIdPerfil As Integer, ByVal intIdAdscripcion As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/insertaUsuarioAplicacion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertaUsuarioAplicacion(ByVal intIdUsuario As Integer, ByVal strPassword As String, ByVal intIdPerfil As Integer, ByVal intIdAdscripcion As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/ActualizarUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ActualizarUsuario(ByVal intIdUsuario As Integer, ByVal strUsuario As String, ByVal strPassword As String, ByVal intIdPerfil As Integer, ByVal intIdAdscripcion As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/EliminarUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EliminarUsuario(ByVal intIdUsuario As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/ConsultarDatosUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultarDatosUsuario(ByVal intIdUsuario As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/ConsultarUsuarios", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultarUsuarios() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/ValidarUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ValidarUsuario(ByVal strUsuario As String, ByVal strPassword As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/BuscaUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function BuscaUsuario(ByVal intIdPersona As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/ConsultaNombreUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultaNombreUsuario(ByVal strUsuario As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultaPerfiles", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultaPerfiles() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultaAdscripcion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultaAdscripcion() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/ConsultaAdscripcionEhijas", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultaAdscripcionEhijas(ByVal intIdUsuario As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/eliminarProyecto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function eliminarProyecto(ByVal intIdProyecto As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/insertaProyecto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertaProyecto( _
                    ByVal imgImagenInfraestructura As Object,  _
                    ByVal intIdTipoServicio As Integer,  _
                    ByVal intIdUsuariosMeta As Integer,  _
                    ByVal strNombreProyecto As String,  _
                    ByVal strProyectoDescripcion As String,  _
                    ByVal strProyectoObjetivo As String,  _
                    ByVal strProyectoInfraestructura As String,  _
                    ByVal strRecursosHumanos As String,  _
                    ByVal ProyectoBeneficiosUsuario As String,  _
                    ByVal ProyectoProductoFinalEsperado As String,  _
                    ByVal strProyectoTiempoDuracion As String,  _
                    ByVal intIdProyectoPosiblesLideres As Integer,  _
                    ByVal intIdAdscripcion As Integer,  _
                    ByVal strMostrarCliente As String,  _
                    ByVal strProyectoVisible As String,  _
                    ByVal intIdUsuario As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/modificaProyecto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function modificaProyecto( _
                    ByVal imgImagenInfraestructura As Object,  _
                    ByVal intIdTipoServicio As Integer,  _
                    ByVal intIdUsuariosMeta As Integer,  _
                    ByVal strNombreProyecto As String,  _
                    ByVal strProyectoDescripcion As String,  _
                    ByVal strProyectoObjetivo As String,  _
                    ByVal strProyectoInfraestructura As String,  _
                    ByVal strRecursosHumanos As String,  _
                    ByVal ProyectoBeneficiosUsuario As String,  _
                    ByVal ProyectoProductoFinalEsperado As String,  _
                    ByVal strProyectoTiempoDuracion As String,  _
                    ByVal intIdProyectoPosiblesLideres As Integer,  _
                    ByVal intIdAdscripcion As Integer,  _
                    ByVal strMostrarCliente As String,  _
                    ByVal strProyectoVisible As String,  _
                    ByVal intIdUsuario As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/insertaSiguienteEstatusProyecto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertaSiguienteEstatusProyecto(ByVal intIdProyecto As Integer, ByVal intIdEstatus As Integer, ByVal intIdUsuario As Integer, ByVal strComentarioProyecto As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/eliminaResumenUnidad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function eliminaResumenUnidad(ByVal Id_Resumen As String, ByVal intIdResumen As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/modificaResumenUnidad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function modificaResumenUnidad(ByVal Id_Resumen As String, ByVal intCostoIndirecto As String, ByVal intIdResumen As Integer, ByVal intIdProyecto As Integer, ByVal intUnidadBruta As Integer, ByVal intAportacion As Integer, ByVal intUnidad As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/eliminaRegistroAnalisisCosto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function eliminaRegistroAnalisisCosto(ByVal idResumen As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/InsertaAnalisisCosto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertaAnalisisCosto(ByVal strRecurso As String, ByVal strUnidadMedida As String, ByVal strCantidad As String, ByVal strCostoUnitario As String, ByVal strDistribuidoEntre As String, ByVal intIdProyecto As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/insertaResumenUnidad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertaResumenUnidad(ByVal intCostoIndirecto As String, ByVal intUnidadBruta As String, ByVal intAportacion As String, ByVal intUnidad As String, ByVal intIdProyecto As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/InsertarComparacionPrecios", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertarComparacionPrecios(ByVal strNombreInstitucion As String, ByVal strPrecioMercado As String, ByVal strDiferenciacion As String, ByVal intIdProyecto As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/eliminarRegistroComparacionPrecios", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function eliminarRegistroComparacionPrecios(ByVal strIdComparacionPrecios As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultarProyecto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultarProyecto(ByVal strIdEstatus As String, ByVal intIdUsuario As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/ConsultaUsuarioMetaProyecto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultaUsuarioMetaProyecto(ByVal intIdProyecto As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/PosibleLiderProyecto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PosibleLiderProyecto(ByVal intIdProyecto As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/ConsultaDatosProyecto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultaDatosProyecto(ByVal intIdProyecto As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultarPuesto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultarPuesto(ByVal intIdAdscripcion As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultarAnalisisCostos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultarAnalisisCostos(ByVal intIdProyecto As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultarResumenUnidadProyecto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultarResumenUnidadProyecto(ByVal intIdProyecto As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultarUsuarioMeta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultarUsuarioMeta() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultarServicios", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultarServicios() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultaEstatus", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultaEstatus() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultaEstatusSiguiente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultaEstatusSiguiente(ByVal intIdProyecto As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultarProyectosRevision", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultarProyectosRevision(ByVal strIdAdscripcion As String, ByVal strIdTipoServicio As String, ByVal strIdUsuarioMeta As String, ByVal strIdEstatus As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/consultarProyectoCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultarProyectoCliente(ByVal strIdTipoServicio As String, ByVal strIdUsuarioMeta As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/ConsultaDatosProyectoCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultaDatosProyectoCliente(ByVal intIdProyecto As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://132.248.180.207/wsfesaoutsorcing/ConsultarComparacionPreciosProyecto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultarComparacionPreciosProyecto(ByVal intIdProyecto As String) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface OutsourcingSoapChannel
        Inherits WSOutsourcing.OutsourcingSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class OutsourcingSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSOutsourcing.OutsourcingSoap)
        Implements WSOutsourcing.OutsourcingSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HelloWorld() As String Implements WSOutsourcing.OutsourcingSoap.HelloWorld
            Return MyBase.Channel.HelloWorld
        End Function
        
        Public Function insertaPersona(ByVal strRfc As String, ByVal strHomoclaveRfc As String, ByVal strNombre As String, ByVal strApellidoPaterno As String, ByVal strApellidoMaterno As String, ByVal strTelefono As String, ByVal strCelular As String, ByVal strCorreoElectronico As String, ByVal strCalle As String, ByVal strColonia As String) As String Implements WSOutsourcing.OutsourcingSoap.insertaPersona
            Return MyBase.Channel.insertaPersona(strRfc, strHomoclaveRfc, strNombre, strApellidoPaterno, strApellidoMaterno, strTelefono, strCelular, strCorreoElectronico, strCalle, strColonia)
        End Function
        
        Public Function consultarPersonas(ByVal strApellidoPaterno As String, ByVal strApellidoMaterno As String, ByVal strNombre As String, ByVal strRfc As String, ByVal strHomoclaveRfc As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultarPersonas
            Return MyBase.Channel.consultarPersonas(strApellidoPaterno, strApellidoMaterno, strNombre, strRfc, strHomoclaveRfc)
        End Function
        
        Public Function consultarColonia(ByVal strCodigoPostal As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultarColonia
            Return MyBase.Channel.consultarColonia(strCodigoPostal)
        End Function
        
        Public Function consultaNombrePersona(ByVal strRfc As String, ByVal strHomoclaveRfc As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultaNombrePersona
            Return MyBase.Channel.consultaNombrePersona(strRfc, strHomoclaveRfc)
        End Function
        
        Public Function insertaUsuario(ByVal intIdPersona As Integer, ByVal strUsuario As String, ByVal strPassword As String, ByVal intIdPerfil As Integer, ByVal intIdAdscripcion As Integer) As String Implements WSOutsourcing.OutsourcingSoap.insertaUsuario
            Return MyBase.Channel.insertaUsuario(intIdPersona, strUsuario, strPassword, intIdPerfil, intIdAdscripcion)
        End Function
        
        Public Function insertaUsuarioAplicacion(ByVal intIdUsuario As Integer, ByVal strPassword As String, ByVal intIdPerfil As Integer, ByVal intIdAdscripcion As Integer) As String Implements WSOutsourcing.OutsourcingSoap.insertaUsuarioAplicacion
            Return MyBase.Channel.insertaUsuarioAplicacion(intIdUsuario, strPassword, intIdPerfil, intIdAdscripcion)
        End Function
        
        Public Function ActualizarUsuario(ByVal intIdUsuario As Integer, ByVal strUsuario As String, ByVal strPassword As String, ByVal intIdPerfil As Integer, ByVal intIdAdscripcion As Integer) As String Implements WSOutsourcing.OutsourcingSoap.ActualizarUsuario
            Return MyBase.Channel.ActualizarUsuario(intIdUsuario, strUsuario, strPassword, intIdPerfil, intIdAdscripcion)
        End Function
        
        Public Function EliminarUsuario(ByVal intIdUsuario As Integer) As String Implements WSOutsourcing.OutsourcingSoap.EliminarUsuario
            Return MyBase.Channel.EliminarUsuario(intIdUsuario)
        End Function
        
        Public Function ConsultarDatosUsuario(ByVal intIdUsuario As Integer) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.ConsultarDatosUsuario
            Return MyBase.Channel.ConsultarDatosUsuario(intIdUsuario)
        End Function
        
        Public Function ConsultarUsuarios() As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.ConsultarUsuarios
            Return MyBase.Channel.ConsultarUsuarios
        End Function
        
        Public Function ValidarUsuario(ByVal strUsuario As String, ByVal strPassword As String) As String Implements WSOutsourcing.OutsourcingSoap.ValidarUsuario
            Return MyBase.Channel.ValidarUsuario(strUsuario, strPassword)
        End Function
        
        Public Function BuscaUsuario(ByVal intIdPersona As Integer) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.BuscaUsuario
            Return MyBase.Channel.BuscaUsuario(intIdPersona)
        End Function
        
        Public Function ConsultaNombreUsuario(ByVal strUsuario As String) As String Implements WSOutsourcing.OutsourcingSoap.ConsultaNombreUsuario
            Return MyBase.Channel.ConsultaNombreUsuario(strUsuario)
        End Function
        
        Public Function consultaPerfiles() As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultaPerfiles
            Return MyBase.Channel.consultaPerfiles
        End Function
        
        Public Function consultaAdscripcion() As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultaAdscripcion
            Return MyBase.Channel.consultaAdscripcion
        End Function
        
        Public Function ConsultaAdscripcionEhijas(ByVal intIdUsuario As Integer) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.ConsultaAdscripcionEhijas
            Return MyBase.Channel.ConsultaAdscripcionEhijas(intIdUsuario)
        End Function
        
        Public Function eliminarProyecto(ByVal intIdProyecto As Integer) As String Implements WSOutsourcing.OutsourcingSoap.eliminarProyecto
            Return MyBase.Channel.eliminarProyecto(intIdProyecto)
        End Function
        
        Public Function insertaProyecto( _
                    ByVal imgImagenInfraestructura As Object,  _
                    ByVal intIdTipoServicio As Integer,  _
                    ByVal intIdUsuariosMeta As Integer,  _
                    ByVal strNombreProyecto As String,  _
                    ByVal strProyectoDescripcion As String,  _
                    ByVal strProyectoObjetivo As String,  _
                    ByVal strProyectoInfraestructura As String,  _
                    ByVal strRecursosHumanos As String,  _
                    ByVal ProyectoBeneficiosUsuario As String,  _
                    ByVal ProyectoProductoFinalEsperado As String,  _
                    ByVal strProyectoTiempoDuracion As String,  _
                    ByVal intIdProyectoPosiblesLideres As Integer,  _
                    ByVal intIdAdscripcion As Integer,  _
                    ByVal strMostrarCliente As String,  _
                    ByVal strProyectoVisible As String,  _
                    ByVal intIdUsuario As Integer) As String Implements WSOutsourcing.OutsourcingSoap.insertaProyecto
            Return MyBase.Channel.insertaProyecto(imgImagenInfraestructura, intIdTipoServicio, intIdUsuariosMeta, strNombreProyecto, strProyectoDescripcion, strProyectoObjetivo, strProyectoInfraestructura, strRecursosHumanos, ProyectoBeneficiosUsuario, ProyectoProductoFinalEsperado, strProyectoTiempoDuracion, intIdProyectoPosiblesLideres, intIdAdscripcion, strMostrarCliente, strProyectoVisible, intIdUsuario)
        End Function
        
        Public Function modificaProyecto( _
                    ByVal imgImagenInfraestructura As Object,  _
                    ByVal intIdTipoServicio As Integer,  _
                    ByVal intIdUsuariosMeta As Integer,  _
                    ByVal strNombreProyecto As String,  _
                    ByVal strProyectoDescripcion As String,  _
                    ByVal strProyectoObjetivo As String,  _
                    ByVal strProyectoInfraestructura As String,  _
                    ByVal strRecursosHumanos As String,  _
                    ByVal ProyectoBeneficiosUsuario As String,  _
                    ByVal ProyectoProductoFinalEsperado As String,  _
                    ByVal strProyectoTiempoDuracion As String,  _
                    ByVal intIdProyectoPosiblesLideres As Integer,  _
                    ByVal intIdAdscripcion As Integer,  _
                    ByVal strMostrarCliente As String,  _
                    ByVal strProyectoVisible As String,  _
                    ByVal intIdUsuario As Integer) As String Implements WSOutsourcing.OutsourcingSoap.modificaProyecto
            Return MyBase.Channel.modificaProyecto(imgImagenInfraestructura, intIdTipoServicio, intIdUsuariosMeta, strNombreProyecto, strProyectoDescripcion, strProyectoObjetivo, strProyectoInfraestructura, strRecursosHumanos, ProyectoBeneficiosUsuario, ProyectoProductoFinalEsperado, strProyectoTiempoDuracion, intIdProyectoPosiblesLideres, intIdAdscripcion, strMostrarCliente, strProyectoVisible, intIdUsuario)
        End Function
        
        Public Function insertaSiguienteEstatusProyecto(ByVal intIdProyecto As Integer, ByVal intIdEstatus As Integer, ByVal intIdUsuario As Integer, ByVal strComentarioProyecto As String) As String Implements WSOutsourcing.OutsourcingSoap.insertaSiguienteEstatusProyecto
            Return MyBase.Channel.insertaSiguienteEstatusProyecto(intIdProyecto, intIdEstatus, intIdUsuario, strComentarioProyecto)
        End Function
        
        Public Function eliminaResumenUnidad(ByVal Id_Resumen As String, ByVal intIdResumen As Integer) As String Implements WSOutsourcing.OutsourcingSoap.eliminaResumenUnidad
            Return MyBase.Channel.eliminaResumenUnidad(Id_Resumen, intIdResumen)
        End Function
        
        Public Function modificaResumenUnidad(ByVal Id_Resumen As String, ByVal intCostoIndirecto As String, ByVal intIdResumen As Integer, ByVal intIdProyecto As Integer, ByVal intUnidadBruta As Integer, ByVal intAportacion As Integer, ByVal intUnidad As Integer) As String Implements WSOutsourcing.OutsourcingSoap.modificaResumenUnidad
            Return MyBase.Channel.modificaResumenUnidad(Id_Resumen, intCostoIndirecto, intIdResumen, intIdProyecto, intUnidadBruta, intAportacion, intUnidad)
        End Function
        
        Public Function eliminaRegistroAnalisisCosto(ByVal idResumen As String) As String Implements WSOutsourcing.OutsourcingSoap.eliminaRegistroAnalisisCosto
            Return MyBase.Channel.eliminaRegistroAnalisisCosto(idResumen)
        End Function
        
        Public Function InsertaAnalisisCosto(ByVal strRecurso As String, ByVal strUnidadMedida As String, ByVal strCantidad As String, ByVal strCostoUnitario As String, ByVal strDistribuidoEntre As String, ByVal intIdProyecto As Integer) As String Implements WSOutsourcing.OutsourcingSoap.InsertaAnalisisCosto
            Return MyBase.Channel.InsertaAnalisisCosto(strRecurso, strUnidadMedida, strCantidad, strCostoUnitario, strDistribuidoEntre, intIdProyecto)
        End Function
        
        Public Function insertaResumenUnidad(ByVal intCostoIndirecto As String, ByVal intUnidadBruta As String, ByVal intAportacion As String, ByVal intUnidad As String, ByVal intIdProyecto As Integer) As String Implements WSOutsourcing.OutsourcingSoap.insertaResumenUnidad
            Return MyBase.Channel.insertaResumenUnidad(intCostoIndirecto, intUnidadBruta, intAportacion, intUnidad, intIdProyecto)
        End Function
        
        Public Function InsertarComparacionPrecios(ByVal strNombreInstitucion As String, ByVal strPrecioMercado As String, ByVal strDiferenciacion As String, ByVal intIdProyecto As Integer) As String Implements WSOutsourcing.OutsourcingSoap.InsertarComparacionPrecios
            Return MyBase.Channel.InsertarComparacionPrecios(strNombreInstitucion, strPrecioMercado, strDiferenciacion, intIdProyecto)
        End Function
        
        Public Function eliminarRegistroComparacionPrecios(ByVal strIdComparacionPrecios As String) As String Implements WSOutsourcing.OutsourcingSoap.eliminarRegistroComparacionPrecios
            Return MyBase.Channel.eliminarRegistroComparacionPrecios(strIdComparacionPrecios)
        End Function
        
        Public Function consultarProyecto(ByVal strIdEstatus As String, ByVal intIdUsuario As Integer) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultarProyecto
            Return MyBase.Channel.consultarProyecto(strIdEstatus, intIdUsuario)
        End Function
        
        Public Function ConsultaUsuarioMetaProyecto(ByVal intIdProyecto As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.ConsultaUsuarioMetaProyecto
            Return MyBase.Channel.ConsultaUsuarioMetaProyecto(intIdProyecto)
        End Function
        
        Public Function PosibleLiderProyecto(ByVal intIdProyecto As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.PosibleLiderProyecto
            Return MyBase.Channel.PosibleLiderProyecto(intIdProyecto)
        End Function
        
        Public Function ConsultaDatosProyecto(ByVal intIdProyecto As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.ConsultaDatosProyecto
            Return MyBase.Channel.ConsultaDatosProyecto(intIdProyecto)
        End Function
        
        Public Function consultarPuesto(ByVal intIdAdscripcion As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultarPuesto
            Return MyBase.Channel.consultarPuesto(intIdAdscripcion)
        End Function
        
        Public Function consultarAnalisisCostos(ByVal intIdProyecto As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultarAnalisisCostos
            Return MyBase.Channel.consultarAnalisisCostos(intIdProyecto)
        End Function
        
        Public Function consultarResumenUnidadProyecto(ByVal intIdProyecto As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultarResumenUnidadProyecto
            Return MyBase.Channel.consultarResumenUnidadProyecto(intIdProyecto)
        End Function
        
        Public Function consultarUsuarioMeta() As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultarUsuarioMeta
            Return MyBase.Channel.consultarUsuarioMeta
        End Function
        
        Public Function consultarServicios() As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultarServicios
            Return MyBase.Channel.consultarServicios
        End Function
        
        Public Function consultaEstatus() As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultaEstatus
            Return MyBase.Channel.consultaEstatus
        End Function
        
        Public Function consultaEstatusSiguiente(ByVal intIdProyecto As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultaEstatusSiguiente
            Return MyBase.Channel.consultaEstatusSiguiente(intIdProyecto)
        End Function
        
        Public Function consultarProyectosRevision(ByVal strIdAdscripcion As String, ByVal strIdTipoServicio As String, ByVal strIdUsuarioMeta As String, ByVal strIdEstatus As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultarProyectosRevision
            Return MyBase.Channel.consultarProyectosRevision(strIdAdscripcion, strIdTipoServicio, strIdUsuarioMeta, strIdEstatus)
        End Function
        
        Public Function consultarProyectoCliente(ByVal strIdTipoServicio As String, ByVal strIdUsuarioMeta As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.consultarProyectoCliente
            Return MyBase.Channel.consultarProyectoCliente(strIdTipoServicio, strIdUsuarioMeta)
        End Function
        
        Public Function ConsultaDatosProyectoCliente(ByVal intIdProyecto As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.ConsultaDatosProyectoCliente
            Return MyBase.Channel.ConsultaDatosProyectoCliente(intIdProyecto)
        End Function
        
        Public Function ConsultarComparacionPreciosProyecto(ByVal intIdProyecto As String) As System.Data.DataSet Implements WSOutsourcing.OutsourcingSoap.ConsultarComparacionPreciosProyecto
            Return MyBase.Channel.ConsultarComparacionPreciosProyecto(intIdProyecto)
        End Function
    End Class
End Namespace
